server:
  port: 8080
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.207:3306/emis?useUnicode=true&serverTimezone=UTC&characterEncoding=utf8&useSSL=true
    username: root
    password: mysql
    default-auto-commit: true
    #指定updates是否自动提交
    auto-commit: true
    maximum-pool-size: 100
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    validation-query: SELECT 1
    test-on-borrow: false
    test-while-idle: true
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 18800
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000

  thymeleaf:
    mode: HTML
    encoding: utf-8
    # thymeleaf缓存 开发时禁用，上线打开
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  activiti:
    check-process-definitions: false

# mybatis对应的映射文件路径
mybatis:
  mapper-locations: classpath*:com/relsol/*/mapper/*.xml
  # mybatis对应的实体类
  type-aliases-package: com.relsol.demo.entity